// <auto-generated />
using System;
using FPTCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPTCanteen.Data.Migrations
{
    [DbContext(typeof(FPTCanteenContext))]
    partial class FPTCanteenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPTCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FPTCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "COM01",
                            IsAvailable = true,
                            Name = "Cơm sườn nướng",
                            Price = 25000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 2,
                            Code = "COM02",
                            IsAvailable = true,
                            Name = "Cơm gà chiên",
                            Price = 22000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COM03",
                            IsAvailable = true,
                            Name = "Cơm chiên dương châu",
                            Price = 20000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PHO01",
                            IsAvailable = true,
                            Name = "Phở bò",
                            Price = 30000m,
                            Unit = "Tô"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PHO02",
                            IsAvailable = true,
                            Name = "Phở gà",
                            Price = 28000m,
                            Unit = "Tô"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MI01",
                            IsAvailable = true,
                            Name = "Mì xào bò",
                            Price = 22000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MI02",
                            IsAvailable = true,
                            Name = "Mì xào hải sản",
                            Price = 25000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 8,
                            Code = "BUN01",
                            IsAvailable = true,
                            Name = "Bún bò Huế",
                            Price = 30000m,
                            Unit = "Tô"
                        },
                        new
                        {
                            Id = 9,
                            Code = "BUN02",
                            IsAvailable = true,
                            Name = "Bún chả",
                            Price = 25000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 10,
                            Code = "CAN01",
                            IsAvailable = true,
                            Name = "Canh chua cá lóc",
                            Price = 18000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 11,
                            Code = "RAU01",
                            IsAvailable = true,
                            Name = "Rau muống xào tỏi",
                            Price = 12000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = 12,
                            Code = "TRA01",
                            IsAvailable = true,
                            Name = "Trà đá",
                            Price = 5000m,
                            Unit = "Ly"
                        },
                        new
                        {
                            Id = 13,
                            Code = "TRA02",
                            IsAvailable = true,
                            Name = "Trà sen",
                            Price = 8000m,
                            Unit = "Ly"
                        },
                        new
                        {
                            Id = 14,
                            Code = "NUOC01",
                            IsAvailable = true,
                            Name = "Nước ngọt",
                            Price = 10000m,
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 15,
                            Code = "SUA01",
                            IsAvailable = true,
                            Name = "Sữa chua uống",
                            Price = 12000m,
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 16,
                            Code = "CAFE01",
                            IsAvailable = true,
                            Name = "Cà phê sữa",
                            Price = 15000m,
                            Unit = "Ly"
                        });
                });

            modelBuilder.Entity("FPTCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FPTCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FPTCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FPTCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPTCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FPTCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
